### ISSUE TITLE
Fix frontend- Rachana

### ISSUE THREAD

**Issue by iracoon** [CIS4301-Project-University-of-Florida/U.S.-Gun-Crime#6]
Get css/jsx working

**Comment by iracoon** [comment]
"start": "PORT=8000 react-app-rewired start",
    "start": "set PORT=8000 && react-app-rewired start", (this is what fixed the css issues for me)

**Comment by AleksandrHovhannisyan** [comment]
@iracoon  `set PORT=8000` will be ignored in non-Windows shells and will default to running the app on port 3000, which would conflict with our server. I'd recommend using WSL in this case to run the client.
